version: '3.2'
services:
    auth_service:
        build: ./Services/AuthService
        image: sandhaka/auth_service
        command: dotnet run --rm
        ports:
            - "5000:5000"
        environment:
            ASPNETCORE_URLS: http://*:5000
            CONNECTION_STRING: "Server=user_db; Port=3306; Database=userdb; Uid=sandhaka; Password=pwd"
        depends_on:
            - user_db
    user_db:
        image: "mysql:latest"
        environment:
            - MYSQL_ROOT_PASSWORD=pwd
            - MYSQL_DATABASE=userdb
            - MYSQL_USER=sandhaka
            - MYSQL_PASSWORD=pwd
        volumes:
            - $HOME/data/userdb:/var/lib/mysql
    resource_test_service:
        build: ./Services/ResourceTestService
        image: sandhaka/resource_test_service
        command: dotnet run --rm
        ports:
            - "9000:9000"
        environment:
            ASPNETCORE_URLS: http://*:9000