version: '3.2'
services:
    # Json Web Tokens authorization server
    auth:
        build: ./Services/AuthService
        image: sandhaka/mymicsapp_auth
        command: dotnet run --rm
        ports:
            - "5000:443"
        environment:
            CONNECTION_STRING: "Server=mysql.data; Port=3306; Database=mymicsapp.Services.identityDb; Uid=sandhaka; Password=pwd"
            ASPNETCORE_ENVIRONMENT: "Development"
        depends_on:
            - mysql.data
    orders:
        build: ./Services/Orders/Orders.Application
        image: "sandhaka/mymicsapp_orders"
        command: dotnet run --rm
        ports:
            - "9000:443"
        environment:
            CONNECTION_STRING: "Server=mysql.data; Port=3306; Database=mymicsapp.Services.ordersDb; Uid=sandhaka; Password=pwd"
            ASPNETCORE_ENVIRONMENT: "Development"
        depends_on:
            - mysql.data
    catalog:
        build: ./Services/Catalog/Catalog.Application
        image: "sandhaka/mymicsapp_catalog"
        command: dotnet run --rm
        ports:
            - "9001:443"
        environment:
            CONNECTION_STRING: "Server=mysql.data; Port=3306; Database=mymicsapp.Services.catalogDb; Uid=sandhaka; Password=pwd"
            ASPNETCORE_ENVIRONMENT: "Development"
        depends_on:
            - mysql.data
    # I'm goind to use the same database for all the services but keep the aggregates separate. 
    # In a production environment I'll plan to use a dedicated one for each microservice
    mysql.data:
        image: "mysql:latest"
        environment:
            - MYSQL_ROOT_PASSWORD=pwd
            - MYSQL_USER=sandhaka
            - MYSQL_PASSWORD=pwd
        volumes:
            - $HOME/data/mymicsapp_db:/var/lib/mysql
        ports:
            - "3306:3306"
    # Angular 2 client running on ngix web server
    web.spa:
        build: ./Clients/Web/spa
        image: sandhaka/mymicsapp_webspa
        ports:
            - "80:80"
        environment:
            CatalogUrl: "https://${DEV_WEB_API_DNS_OR_IP}:9001"
            OrdersUrl: "https://${DEV_WEB_API_DNS_OR_IP}:9000"
            AuthUrl: "https://${DEV_WEB_API_DNS_OR_IP}:5000"
        volumes:
            - $HOME/mymicsapp/nginx-logs:/var/log/nginx