version: '3.2'
services:
    auth_service:
        build: ./Services/AuthService
        image: sandhaka/auth_service
        command: dotnet run --rm
        ports:
            - "5000:5000"
        environment:
            ASPNETCORE_URLS: http://*:5000
            CONNECTION_STRING: "Server=db; Port=3306; Database=testdb; Uid=sandhaka; Password=pwd"
        depends_on:
            - db
    db:
        image: "mysql:latest"
        environment:
            - MYSQL_ROOT_PASSWORD=pwd
            - MYSQL_DATABASE=testdb
            - MYSQL_USER=sandhaka
            - MYSQL_PASSWORD=pwd
        volumes:
            - $HOME/data/db-auth:/var/lib/mysql
        ports:
            - "3306:3306"
    resource_test_service:
        build: ./Services/ResourceTestService
        image: sandhaka/resource_test_service
        command: dotnet run --rm
        ports:
            - "9000:9000"
        environment:
            ASPNETCORE_URLS: http://*:9000