version: '3.2'
services:
    auth:
        build: ./Services/AuthService
        image: sandhaka/mymicsapp_auth
        command: dotnet run --rm
        ports:
            - "5000:443"
        environment:
            CONNECTION_STRING: "Server=mysql.data; Port=3306; Database=mymicsapp.Services.identityDb; Uid=sandhaka; Password=pwd"
        depends_on:
            - mysql.data
    orders:
        build: ./Services/Orders/Orders.Application
        image: "sandhaka/mymicsapp_orders"
        command: dotnet run --rm
        ports:
            - "9000:443"
        environment:
            CONNECTION_STRING: "Server=mysql.data; Port=3306; Database=mymicsapp.Services.ordersDb; Uid=sandhaka; Password=pwd"
        depends_on:
            - mysql.data
    # I'm goind to use the same database for all the services but keep the aggregates separate. 
    # In a production environment I'll plan to use a dedicated one for each microservice
    mysql.data:
        image: "mysql:latest"
        environment:
            - MYSQL_ROOT_PASSWORD=pwd
            - MYSQL_USER=sandhaka
            - MYSQL_PASSWORD=pwd
        volumes:
            - $HOME/data/mymicsapp_db:/var/lib/mysql
        ports:
            - "3306:3306"