version: '3.2'
services:
  fluentd:
    build: ./fluentd
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
  elasticsearch:
    image: elasticsearch
  kibana:
    image: kibana
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"