version: '3.2'
services:
    auth:     
        environment:
            ASPNETCORE_ENVIRONMENT: "Production"   
        logging:
            driver: "fluentd"
            options:
                tag: auth
    orders:
        environment:
            ASPNETCORE_ENVIRONMENT: "Production"  
        logging:
            driver: "fluentd"
            options:
                tag: orders
    catalog:     
        environment:
            ASPNETCORE_ENVIRONMENT: "Production"      
        logging:
            driver: "fluentd"
            options:
                tag: catalog
    basket:
        environment:
            ASPNETCORE_ENVIRONMENT: "Production"      
        networks:
            - mymsc.network        
        logging:
            driver: "fluentd"
            options:
                tag: basket
    sql.data:      
        logging:
            driver: "fluentd"
            options:
                tag: sql.data
    redis.data:
        logging:
            driver: "fluentd"
            options:
                tag: redis.data
    web.spa:
        logging:
            driver: "fluentd"
            options:
                tag: web.spa