version: '3.2'
services:
    auth:
        image: sandhaka/mymicsapp_auth
        command: dotnet run --rm
        ports:
            - "5005:443"
        environment:  
            ASPNETCORE_ENVIRONMENT: "Production"          
            CONNECTION_STRING: "Server=sql_data,1433; Initial Catalog=mymicsapp.Services.identityDb; User Id=sa; Password=Password&1"
        networks:
          - mymsc_network    
        deploy:
          replicas: 1        
        logging:
            driver: "fluentd"
            options:
                tag: auth        
        secrets:    
            - cert
            - cert_pwd                               
    orders:
        image: sandhaka/mymicsapp_orders
        command: dotnet run --rm
        environment:  
            ASPNETCORE_ENVIRONMENT: "Production"          
            CONNECTION_STRING: "Server=sql_data,1433; Initial Catalog=mymicsapp.Services.ordersDb; User Id=sa; Password=Password&1"
            REDIS_CONNECTION: "redis_data"
        networks:
          - mymsc_network   
        deploy:
          replicas: 1  
        logging:
            driver: "fluentd"
            options:
                tag: orders        
        secrets:    
            - cert
            - cert_pwd                                          
    catalog:
        image: sandhaka/mymicsapp_catalog
        command: dotnet run --rm
        environment: 
            ASPNETCORE_ENVIRONMENT: "Production"          
            CONNECTION_STRING: "Server=sql_data,1433; Initial Catalog=mymicsapp.Services.catalogDb; User Id=sa; Password=Password&1"
            REDIS_CONNECTION: "redis_data"
        networks:
          - mymsc_network   
        deploy:
          replicas: 1   
        logging:
            driver: "fluentd"
            options:
                tag: catalog                   
        secrets:    
            - cert
            - cert_pwd                               
    basket:
        image: sandhaka/mymicsapp_basket
        command: dotnet run --rm
        environment:
            ASPNETCORE_ENVIRONMENT: "Production"          
            REDIS_CONNECTION: "redis_data"
        networks:
          - mymsc_network   
        deploy:
          replicas: 1   
        logging:
            driver: "fluentd"
            options:
                tag: basket     
        secrets:    
            - cert
            - cert_pwd                                          
    sql_data:
        image: microsoft/mssql-server-linux
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "Password&1"
        volumes:
            - sql_data.vol:/var/opt/mssql
        networks:
          - mymsc_network      
        deploy:
          replicas: 1    
        logging:
            driver: "fluentd"
            options:
                tag: sql.data                           
    redis_data:
        image: redis
        networks:
          - mymsc_network               
        deploy:
          replicas: 1     
        logging:
            driver: "fluentd"
            options:
                tag: redis.data           
    web_spa:
        image: sandhaka/mymicsapp_webspa:deploy      
        ports:
            - "443:443"
        volumes:
            - nginx.logs.vol:/var/log/nginx
        networks:
          - mymsc_network   
        deploy:
          replicas: 1
        logging:
            driver: "fluentd"
            options:
                tag: web.spa                   
    api_gw:
        image: sandhaka/mymicsapp_apigw
        environment: 
            ASPNETCORE_ENVIRONMENT: "Production"                 
        ports:
          - "3000:443"   
        volumes:
            - nginx.logs.vol:/var/log/nginx
        networks:
          - mymsc_network   
        deploy:
          replicas: 1
        logging:
            driver: "fluentd"
            options:
                tag: web.spa  
        secrets:    
            - cert
            - cert_pwd                             

volumes:
    sql_data.vol:
    nginx.logs.vol:

networks: 
    mymsc_network:

secrets:
    cert: 
        file: ./certificates/dev.boltjwt.pfx
    cert_pwd:
        file: ./certificates/dev.boltjwt.passphrase